# Generated by Django 4.2.7 on 2024-11-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productandservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
