# Generated by Django 4.2.7 on 2024-11-21 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_productandservice_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(help_text='e.g., Size, Color', max_length=100)),
                ('attribute_value', models.CharField(help_text='e.g., Large, Red', max_length=100)),
                ('additional_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Additional price for this variant', max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('quantity_available', models.IntegerField(default=0, help_text='Stock quantity for this variant')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='sales.productandservice')),
            ],
        ),
    ]
