version: '3.8'

services:
  grow:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: grow_backend
    command: sh -c "gunicorn grow.wsgi --bind 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

  cron:
    build: .
    container_name: grow_cron
    command: cron -f
    volumes:
      - .:/app
    depends_on:
      - grow
