version: '3.8'

services:
  grow:
    image: grow-api-services
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: grow_backend
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      retries: 3
      start_period: 10s

  cron:
    build: .
    container_name: grow_cron
    command: ["sh", "-c", "python manage.py crontab add && cron -f"]
    volumes:
      - .:/app
    depends_on:
      - grow