import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  let autocomplete: any;
  let onPlaceChange = () => {
    var place = autocomplete.getPlace();
    console.log(place);
  };
  const initMap = () => {
    autocomplete = new google.maps.places.Autocomplete(
      document.getElementById("autocomplete"),
      {
        types: ["establishment"],
        componentRestrictions: { country: ["AU"] },
        field: ["place_id", "geometry", "name"],
      }
    );
    autocomplete.addListener("place_changed", onPlaceChange);
  };
  return (
    <html lang="en">
      <script
        async
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCM-uK8cogx4TL4e5QW2X3Av3OxvMpnxik&libraries=places&callback=initMap"
      ></script>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
