# Generated by Django 4.2.7 on 2023-11-22 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_business_owner_business_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='business',
            unique_together={('owner', 'business_address')},
        ),
    ]
