# Generated by Django 4.2.7 on 2024-01-29 00:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_redirection_alter_address_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redirection',
            name='id',
        ),
        migrations.AddField(
            model_name='redirection',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
