# Generated by Django 4.2.7 on 2024-01-29 00:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20240128_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirection',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, unique=True),
        ),
    ]
