# Generated by Django 4.2.7 on 2024-08-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_oauthaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iss', models.CharField(max_length=255)),
                ('azp', models.CharField(max_length=255)),
                ('aud', models.CharField(max_length=255)),
                ('sub', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('email_verified', models.BooleanField()),
                ('at_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('picture', models.URLField(blank=True, max_length=500, null=True)),
                ('given_name', models.CharField(blank=True, max_length=255, null=True)),
                ('family_name', models.CharField(blank=True, max_length=255, null=True)),
                ('iat', models.IntegerField()),
                ('exp', models.IntegerField()),
            ],
        ),
    ]
