# Generated by Django 4.2.7 on 2024-08-23 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_socialprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthaccount',
            name='social_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.socialprofile'),
        ),
    ]
