# Generated by Django 4.2.7 on 2024-08-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_oauthaccount_social_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_days',
            field=models.JSONField(blank=True, default={'f': True, 'm': True, 's': True, 't': True, 'th': True, 'w': True}, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='business_hours',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='facebook_account_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='insta_account_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='business',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
