# Generated by Django 4.2.7 on 2024-08-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_business_business_days_business_business_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_days',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
