# Generated by Django 4.2.7 on 2024-09-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_oauthaccount_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthaccount',
            name='refresh_token',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
