# Generated by Django 4.2.7 on 2024-08-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnx', '0004_leadresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadresponse',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Canceled', 'Canceled'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Archived', 'Archived')], default='Pending', max_length=10),
        ),
    ]
