name: Deploy Django Backend to EC2

on:
  push:
    branches:
      - main
    # paths:
    #   - "grow-api-service/**" # Only run when backend changes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          curl -fsSL https://get.docker.com | sudo sh
          sudo usermod -aG docker $USER

      - name: Build and Save Docker Image
        run: |
          cd grow-api-service
          docker build -t ${{ secrets.DOCKER_IMAGE_NAME }} .
          docker save ${{ secrets.DOCKER_IMAGE_NAME }} | gzip > image.tar.gz

      - name: Set Up SSH and Transfer Image
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          scp -i ~/.ssh/id_rsa grow-api-service/image.tar.gz ubuntu@${{ secrets.EC2_HOST }}:~/image.tar.gz

      - name: Deploy on EC2
        run: |
          ssh -i ~/.ssh/private_key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          docker load < ~/image.tar.gz
          cd ~/grow-api-service
          docker-compose down
          docker-compose up -d --build
          EOF
