name: Deploy Django Backend to EC2

on:
  push:
    branches:
      - main
    # paths:
    #   - "grow-api-service/**" # Only run when backend changes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          curl -fsSL https://get.docker.com | sudo sh
          sudo usermod -aG docker $USER

      - name: Build and Save Docker Image
        run: |
          cd grow-api-service
          docker build -t ${{ secrets.DOCKER_IMAGE_NAME }} .
          docker save ${{ secrets.DOCKER_IMAGE_NAME }} | gzip > image.tar.gz

      - name: Set Up SSH and Transfer Image
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          scp -i private_key.pem grow-api-service/image.tar.gz ubuntu@${{ secrets.EC2_HOST }}:~/image.tar.gz

      - name: Deploy on EC2
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh -i private_key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          docker load < ~/image.tar.gz
          docker-compose -f ~/grow-api-service/docker-compose.yml down
          docker-compose -f ~/grow-api-service/docker-compose.yml up -d --build
          EOF
